//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NXLevel.LMS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assignment
    {
        public int assignmentId { get; set; }
        public bool enabled { get; set; }
        public string title { get; set; }
        public bool availCoursesInOrder { get; set; }
        public bool allowSelfRegister { get; set; }
        public string registerCode { get; set; }
        public Nullable<System.DateTime> dueDate { get; set; }
        public bool sendEmailOnAssigned { get; set; }
        public bool sendEmailPeriodic { get; set; }
        public Nullable<int> periodicDays { get; set; }
        public bool sendEmailNearDueDate { get; set; }
        public Nullable<int> nearDueDateDays { get; set; }
        public bool sendEmailOnDueDate { get; set; }
        public bool sendEmailOverdue { get; set; }
        public System.DateTime timestamp { get; set; }
        public Nullable<System.DateTime> dueEmailSent { get; set; }
        public Nullable<System.DateTime> periodicEmailSent { get; set; }
        public Nullable<System.DateTime> nearDueDateEmailSent { get; set; }
        public Nullable<System.DateTime> sendOverdueEmailSent { get; set; }
        public int type { get; set; }
        public string description { get; set; }
    }
}
