//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NXLevel.LMS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Courses_Usage
    {
        public int rowId { get; set; }
        public int assignmentId { get; set; }
        public int courseId { get; set; }
        public int userId { get; set; }
        public string suspendData { get; set; }
        public string lessonLocation { get; set; }
        public string lessonStatus { get; set; }
        public Nullable<System.TimeSpan> totalUsage { get; set; }
        public System.DateTime startDate { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
    }
}
