//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NXLevel.LMS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Courses_Scores
    {
        public int rowId { get; set; }
        public int assignmentId { get; set; }
        public int courseId { get; set; }
        public int userId { get; set; }
        public Nullable<decimal> score { get; set; }
        public System.DateTime dateStamp { get; set; }
    }
}
