//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NXLevel.LMS.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public short courseId { get; set; }
        public string userCode { get; set; }
        public string title { get; set; }
        public string url { get; set; }
        public string language { get; set; }
        public bool enabled { get; set; }
        public string description { get; set; }
        public Nullable<int> browserWidth { get; set; }
        public Nullable<int> browserHeight { get; set; }
        public System.DateTime timestamp { get; set; }
        public short type { get; set; }
        public string extra1 { get; set; }
        public string extra2 { get; set; }
    }
}
